<?php
$BDURL = "localhost";
$BDUSER = "root";
$BDPASSWORD = "8520";
$BDNAME = "padel";

$PUBLICKEY = "6LclgdESAAAAAPO1GX1vx52lCEjeTG0AUlWC6-o3";
$PRIVATEKEY = "6LclgdESAAAAAG5ktRzJnf7u6Zk-I86bjKC-29DG";

$MAXDURACION = 120; //en minutos
$MAXCANCELACION = 1; //en horas
$PERIODORESERVA = 7; //en dias

$MAXDURACION_ADMIN = 5000; //en minutos
$MAXCANCELACION_ADMIN = 50000; //en horas
$PERIODORESERVA_ADMIN = 10000; //en dias
$PERIODOPASADO_ADMIN = 10000; // en dias

$RESERVASPORDIA = 3;
$MINUTOSPORDIA = 210;

$PRECIOHORA = 13.33333333333333; //euros
$ABIERTODESDE = 8; //8am
$ABIERTODESDEM = 0;
$ABIERTOHASTA = 0; //0am
$ABIERTOHASTAM = 0;
$INTERVALO = 30;

$RELLENO = 6; //longitud minima al mostrar una ID
$CANTIDAD_RESERVAS = 30;
$CANTIDAD_USUARIOS = 30;

$EMAILCONTACTO = "cristian64@gmail.com";
?>
